const BUYING_PRICE_ONE_LEMON = 0.4;
const BUYING_PRICE_ONE_CUP_SUGAR = 0.4;
const BUYING_PRICE_ONE_ICE_CUBE = 0.02;

export default {
  BUYING_PRICE_ONE_LEMON,
  BUYING_PRICE_ONE_CUP_SUGAR,
  BUYING_PRICE_ONE_ICE_CUBE
};
